language: node_js
node_js:
  - "10"
before_script:
  - npm install -g gulp-cli
script: gulp build
deploy:
  provider: releases
  file_glob: true
  file: dist/*
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: true